---
kind: secret
name: kubeconfig

get:
  path: buildx
  name: kubeconfig

---
kind: pipeline
name: default

services:
  - name: docker
    image: docker:19.03.3-dind
    entrypoint:
      - dockerd
    command:
      - --dns=8.8.8.8
      - --dns=8.8.4.4
      - --mtu=1440
      - --log-level=error
    privileged: true
    volumes:
      - name: docker-socket
        path: /var/run

steps:
  - name: setup-ci
    image: autonomy/build-container:latest
    commands:
      - git fetch --tags
      - install-ci-key
      - setup-buildx-amd64-arm64
    environment:
      SSH_KEY:
        from_secret: ssh_key
    volumes:
      - name: docker-socket
        path: /var/run
      - name: docker
        path: /root/.docker/buildx
      - name: ssh
        path: /root/.ssh

  - name: build-pull-request
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make
    when:
      event:
        include:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run
      - name: docker
        path: /root/.docker/buildx
      - name: ssh
        path: /root/.ssh

  - name: build-and-publish
    image: autonomy/build-container:latest
    pull: always
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login --username "$${DOCKER_USERNAME}" --password "$${DOCKER_PASSWORD}"
      - make PUSH=true
    when:
      event:
        exclude:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run
      - name: docker
        path: /root/.docker/buildx
      - name: ssh
        path: /root/.ssh

volumes:
  - name: docker-socket
    temp: {}
  - name: docker
    temp: {}
  - name: ssh
    temp: {}
---
kind: pipeline
name: notify

clone:
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: proj-talos-maintainers
    when:
      status:
        - success
        - failure

trigger:
  status:
    - success
    - failure

depends_on:
  - default
