---
kind: pkgfile.Build
spec:
  targets:
    - tools
    - llvm
    - tools-ca-certificates
    - tools-cpio
    - tools-kmod
    - tools-libcap
    - tools-libselinux
    - tools-libsepol
    - tools-openssl
    - tools-pcre2
    - tools-squashfs-tools
    - tools-tar
    - tools-util-linux
    - tools-xz
    - tools-zlib-ng
    - tools-zstd
  reproducibleTargetName: reproducibility
---
kind: common.Renovate
spec:
  packageRules:
    - matchPackageNames:
        - golang/go
        - mirror/ncurses
        - PCRE2Project/pcre2
        - plougher/squashfs-tools
        - SELinuxProject/selinux
        - pkgconf/pkgconf
        - git://git.savannah.gnu.org/make.git
        - git://git.kernel.org/pub/scm/utils/util-linux/util-linux.git
        - git://git.savannah.gnu.org/automake.git
        - git://git.savannah.gnu.org/bison.git
        - git://git.savannah.gnu.org/coreutils.git
        - git://git.savannah.gnu.org/diffutils.git
        - git://sourceware.org/git/elfutils.git
        - git://git.savannah.gnu.org/gettext.git
        - git://git.savannah.gnu.org/gperf.git
        - git://git.savannah.gnu.org/grep.git
        - git://git.savannah.gnu.org/gzip.git
        - git://git.kernel.org/pub/scm/devel/pahole/pahole.git
        - git://git.savannah.gnu.org/patch.git
        - git://git.savannah.gnu.org/sed.git
        - git://git.savannah.gnu.org/texinfo.git
        - git://git.kernel.org/pub/scm/libs/libcap/libcap.git
        - git://git.savannah.gnu.org/autoconf.git
        - git://git.savannah.gnu.org/bash.git
        - https://gitlab.kitware.com/cmake/cmake.git
        - git://git.savannah.gnu.org/libunistring.git
      versioning: 'regex:^(?<major>\d+)\.(?<minor>\d+)\.?(?<patch>\d+)?$'
    - matchPackageNames:
        - git://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git
        - gentoo/gpep517
      versioning: 'regex:^(?<major>\d+)\.?(?<minor>\d+)?\.?(?<patch>\d+)?$'
    - matchPackageNames:
        - curl/curl
        - libexpat/libexpat
        - file/file
        - thom311/libnl
        - git://git.savannah.gnu.org/cpio.git
        - git://git.savannah.gnu.org/tar.git
      versioning: 'regex:^(?<major>\d+)_(?<minor>\d+)_?(?<patch>\d+)?$'
    - matchPackageNames:
        - Perl/perl5
      versioning: 'regex:^(?<major>\d+)\.(?<minor>\d[02468]+)\.(?<patch>\d+)$'
    - matchPackageNames:
        - https://salsa.debian.org/clint/fakeroot.git
      versioning: 'regex:^(?<major>\d+)\.(?<minor>\d+)\.?(?<patch>\d+)?\.?(?<build>\d+)?$'
    - matchPackageNames:
        - homebrew/ca-certificates
      versioning: 'regex:^(?<major>\d+)-(?<minor>\d+)-(?<patch>\d+)$'
